### ISSUE TITLE
Awaiting json data

### ISSUE THREAD

**Issue by ezerw** [timdows/MMM-JsonTable#1]
Hey, love this module, but couldn't get it to work.

My origin: `https://api.myjson.com/bins/z68sj`
My config: 
```
config: {
    url: 'https://api.myjson.com/bins/z68sj'
}
```
But getting `Awaiting json data` on the screen..

**Comment by timdows** [comment]
The console error indicates what is wrong
![2018-04-25 10_59_00](https://user-images.githubusercontent.com/9577532/39236008-d31380ee-4877-11e8-80ed-6df2c198b4ab.png)

If you change the config to:
```
		{
			module: 'MMM-JsonTable',
			position: 'bottom_right',
			header: 'Test',
			config: {
				url: 'https://api.myjson.com/bins/z68sj',
				arrayName: 'items', // Optional
				//tryFormatDate: true
			}
		},
```
it will work.

I might change some code to detect that an object is given and not an array

**Comment by timdows** [comment]
I also made a nicer error to prevent this from happening in the future again
https://github.com/timdows/MMM-JsonTable/commit/74c321f2f106ea669371b19bcc1ac5d3a5c169d5
