### ISSUE TITLE
HELP- MM on a Windows 8 PC

### ISSUE THREAD

**Issue by Sharktooth08** [timdows/MMM-JsonTable#10]
Just now learning to code. 
I can get the table to show on the display but it is showing as waiting on Json data. 

I am using a local hosted file. To test it, i put the Raw Json data in  a JSON file but still no luck. 

Is there a way to check to see if the file is being reached or any trouble shooting ideas you can give would be great.

**Comment by timdows** [comment]
You should debug what the jsonData is that gets into the MMM-JsonTable.js
With Chrome you can debug the javascript functions, example:

![image](https://user-images.githubusercontent.com/9577532/78792796-dea8d400-79b1-11ea-8e3e-153c8398aa3b.png)

Otherwise I need a bit more knowledge of your configuration to help you

**Comment by Sharktooth08** [comment]
I wanted to attempt to figure out the debugger before replying. I can get into the chrome debugger but I'm not sure what you want me to do next.

I'm going to  run magicmirror on  Windows 8. The Jason data I put into the actual module folder and the I'm using the following url -http://localhost:8080/modules/data.json ---. I removed all the modules except for this one to try to troubleshoot. When I put the URL on chrome it does pull up the json data. Can you give me the right direction to debug in chrome 
![15867535305914896615336107706339](https://user-images.githubusercontent.com/63277728/79093079-52c7dc80-7d10-11ea-8b98-5ea2cd74cbaa.jpg)
![Uploading 15867535681298511790662850095394.jpg…]()

**Comment by Sharktooth08** [comment]
In the console it says this 
![Uploading 1586753827261447287003821389809.jpg…]()

**Comment by Sharktooth08** [comment]
I was able to figure out the object, like your pic I think. It shows this ----
method: "POST"
uri: "http://localhost:8080/socket.io/?EIO=3&transport=polling&t=N5nzW95&sid=2fZ4wRgig8UHw1CPAAAB"
xd: false
xs: false
async: true
data: "85:42/MMM-JsonTable,["MMM-JsonTable_GET_JSON","http://localhost:8080/modules/data.json"]"
agent: false
isBinary: false
supportsBinary: true
enablesXDR: false
withCredentials: true
requestTimeout: undefined
pfx: null
key: null
passphrase: null
cert: null
ca: null
ciphers: null
rejectUnauthorized: true
extraHeaders: undefined
xhr: XMLHttpRequest {readyState: 1, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}
index: 3
__proto__: Object

**Comment by timdows** [comment]
Can you upload (a part of) what is in: http://localhost:8080/modules/data.json 

It might be that you do not need to configure the optional arrayName parameter in the config.json

**Comment by timdows** [comment]
Close due to inactivity
