### ISSUE TITLE
Get Json from Google "awating" issue

### ISSUE THREAD

**Issue by emrahaslan** [timdows/MMM-JsonTable#13]
Hello, I'm trying to retrieve my sheet from google spreadsheets , but module says "awaiting"

The data in "entry/feed/gsx.." category, I'm not sure what is wrong with my code, but needs your touches.

I also need create loop for bringing  with prefix "gsx " values.

URL

https://spreadsheets.google.com/feeds/list/1dVwsdP3K49XGTaixhTTzuybEz4nFubtQzB_Qa32c4ZM/od6/public/values?alt=json

` {
    module: 'MMM-JsonTable',
    position: 'top_left',
    header: 'Majken',
    config: {
        url: 'https://spreadsheets.google.com/feeds/list/1dVwsdP3K49XGTaixhTTzuybEz4nFubtQzB_Qa32c4ZM/od6/public/values?alt=json', // Required
        arrayName: 'object/feed/entry' // Optional
    }
},
`

![image](https://user-images.githubusercontent.com/54321532/89352329-7dbdae00-d6bc-11ea-908b-80c2019dfc45.png)

**Comment by timdows** [comment]
Its complicated to make this nested array of objects visible in MMM-JsonTable, but I managed

![image](https://user-images.githubusercontent.com/9577532/89392471-dbc4b280-d709-11ea-9692-4095349f5882.png)

I made 3 code changes:

https://github.com/timdows/MMM-JsonTable/blob/master/MMM-JsonTable.js#L59
Get the nested array outside of the configuration
```javascript
		var items = this.jsonData.feed.entry;
		// if (this.config.arrayName) {
		// 	items = this.jsonData[this.config.arrayName];
		// }
		// else {
		// 	items = this.jsonData;
		// }
```

https://github.com/timdows/MMM-JsonTable/blob/master/MMM-JsonTable.js#L87
Only show if it starts with gsx
```javascript
			if (!key.startsWith("gsx")) {
				continue;
			}
			var cell = document.createElement("td");
```

https://github.com/timdows/MMM-JsonTable/blob/master/MMM-JsonTable.js#L98
Force to use the $t
```javascript
valueToDisplay = jsonObject[key].$t;
```

**Comment by emrahaslan** [comment]
Hi timdows,

I tried all your steps carefully, but module always says "Awating Json data ". I think data is not coming, but it looks you succeed it.

Configuration

`{
		module: 'MMM-JsonTable',
		position: 'top_right',
		header: 'Inhabitant Information',
		config: {
			url: 'https://spreadsheets.google.com/feeds/list/1dVwsdP3K49XGTaixhTTzuybEz4nFubtQzB_Qa32c4ZM/od6/public/values?alt=json', // Required
			arrayName: '' // Get the nested array outside of the configuration Optional
		}
                }


.js file Line59

`var items  =[];
		//for google sheets
	    items = this.jsonData.feed.entry;
	  
		//commented for google sheets
		//var items = [];
		//if (this.config.arrayName) {
			//items = this.jsonData[this.config.arrayName];
		//}
		//else {
			//items = this.jsonData;
		//}
`

Line : 100
`getTableRow: function (jsonObject) {
		var row = document.createElement("tr");
		for (var key in jsonObject) {
			
			//added for googlesheets
			
			if (!key.startsWith("gsx")) {
				continue;
			}
			`

Line : 117
`else if (this.config.tryFormatDate) {
				//commented for google sheets
				//valueToDisplay = this.getFormattedValue(jsonObject[key]);
					//added for googlesheets
				valueToDisplay = jsonObject[key].$t;
			}
			else {
				if ( this.config.keepColumns.length == 0 || this.config.keepColumns.indexOf(key) >= 0 ){
					//commented for google sheets
					//valueToDisplay = jsonObject[key];
					//added for googlesheets
					valueToDisplay = jsonObject[key].$t;
				}
			}`

**Comment by emrahaslan** [comment]
I re-installed module and try your steps again, now its works. thanks for your support

![image](https://user-images.githubusercontent.com/54321532/89437014-b195e380-d74f-11ea-81e0-42c7c7f7f83b.png)

**Comment by emrahaslan** [comment]
Great Help
