### ISSUE TITLE
How to change moduleName

### ISSUE THREAD

**Issue by emrahaslan** [timdows/MMM-JsonTable#14]
Hi again

I want to change that module name, here are my steps, but it doesnt work.

1. Changed config array module
`{
       module: 'MMM-JsonTable-2',
       position: 'bottom_left',
       header: 'Test Result',
       config: { 
       url: 'https://spreadsheets.google.com/feeds/list/1dVwsdP3K49XGTaixhTTzuybEz4nFubtQzB_Qa32c4ZM/2/public/values?alt=json',
       arrayName: 'entry'
          
        }

2- changed /module directory name to `MMM-JsonTable-2
3- Change Js name to "MMM-JsonTable-2.js"
4- Inside the Js, changed register module name to "MMM-JsonTable-2"

`Module.register("MMM-JsonTable-2", {`

I 'didn't touch node_helper.js 

when I run the code , it doesnot work. (show loading)

Please help me on it

**Comment by timdows** [comment]
Do you want to show the module 2 times?
In that case, just add multiple configurations. There is no need to change the module name.

**Comment by emrahaslan** [comment]
Thanks. It worked when I try to change module name

**Comment by emrahaslan** [comment]
Thanks for assist me.
