### ISSUE TITLE
Descriptive Row not showing. 

### ISSUE THREAD

**Issue by alexsquared** [timdows/MMM-JsonTable#16]
This is the data from the json file I am incorporating. 

  "data": [
    [
      "2020-10-30 07:46",
      75.79,
      35.00,
      46.20,
      71.92
    ]
  ]

First off, if there is a way for it to omit the second line of data (75.79) that would be ideal as it is redundant and confusing.  Second, i used this string in my config, however, the descriptive row didn't populate. any thoughts? 

url: 'http://10.0.1.150/transfer/log.json?start-time=0&end-time=60', // Required
				arrayName: 'data', // Optional
				tryFormatDate: 'true',
				descriptiveRow: '<tr><td>Date</td><td>Temp</td><td>Dewpoint</td><td>Humidity</td><td>Temp</td></tr>'

**Comment by timdows** [comment]
The "data" object contains a nested array

For example, if you use "devices", it will work, that is because the devices array contains objects

You have to change the data array to be an array of objects
Or we have to look for another solution

**Comment by timdows** [comment]
And an example of the descriptive row is

```html
		descriptiveRow: '<tr><td>Name</td><td>Today</td><td>ThisWeek</td><td>LastWeek</td><td>ThisMonth</td><td>LastMonth</td></tr>'

```

**Comment by GCE-Galotta** [comment]
I'm not sure if this was solved or not, but I cannot get the descriptiveRow to show either. Here is my json:
```
{ 
    "Daten": [
        {
        "icon":"fa-thermometer-half",
        "value": "56.9",
        "unit": "°C",
        "lastUpdate": "17:10:17"
        },
        {
        "icon":"fa-microchip",
        "value": "14",
        "unit": "%",
        "lastUpdate": "17:10:19"
        },
        {
        "icon":"fa-memory",
        "value": "106.325",
        "unit": "MB",
        "lastUpdate": "17:10:17"
        }
    ]
}
```

And my mmm-jsonTable config:
```javascript
{
    module: 'MMM-JsonTable',
    position: 'top_right',
    header: 'Raspi-Status',
    config: {
        url: 'http://192.168.178.99:1880/daten.json', // Required
        arrayName: 'Daten', // Optional
        tryFormatDate: false,
        descriptiveRow: '<tr><td>Messung</td><td>Wert</td><td>Einheit</td><td>Zeitstempel</td></tr>'
    }
},
```
And the result:
![image](https://user-images.githubusercontent.com/48594153/99909145-21bc7b00-2ce7-11eb-8e91-e127def53dab.png)

**Comment by GCE-Galotta** [comment]
any idea @timdows ?

**Comment by orbekkum** [comment]
Doesn't look like this is implemented in the code.
I added this piece of code to get it to work:
`                if (this.config.descriptiveRow) {
                        var header = table.createTHead();
                        header.innerHTML = this.config.descriptiveRow;
                } `

**Comment by lsaadeh** [comment]
I'm also have this issue.

`{
      module: 'MMM-JsonTable',
      position: 'top_center',
      header: 'NSW Covid',
      config: {
        url: '<URL removed>',
        arrayName: 'data',
        keepColumns: ['Recovered', 'Deaths', 'NewCases', 'Cases'],
				descriptiveRow: '<tr><td>Recovered</td><td>Deaths</td><td>NewCases</td><td>Cases</td></tr>'
      }
    },`

**Comment by manifestinteractive** [comment]
For anyone still wondering about this, @orbekkum is 100% correct, `descriptiveRow` was never implemented, meaning it will never work.

I have submitted a Pull Request to resolve this issue ( https://github.com/timdows/MMM-JsonTable/pull/19 ).

For those that just want this working, you can replace your `MMM-JsonTable.json` file with this one:  https://github.com/manifestinteractive/MMM-JsonTable/blob/master/MMM-JsonTable.js 

CC: @alexsquared, @lsaadeh, @orbekkum, @GCE-Galotta

**Comment by timdows** [comment]
Thanks @manifestinteractive! 

Let me know if anyone has any more feature requests!
But I'll close this for noe!
