### ISSUE TITLE
Blinking when update

### ISSUE THREAD

**Issue by flopp999** [timdows/MMM-JsonTable#25]
Very nice module thanks.

I don't know if this is only for your module, since I don't use many other modules with update every 10 second, like I have with your module.

Is it possible to disable the blink?

**Comment by KristjanESPERANTO** [comment]
I have created a Pull Request. If @timdows accepts it, you can set the animationSpeed to `0` in the config file, then it will no longer blink.

**Comment by timdows** [comment]
@flopp999 @KristjanESPERANTO 
The PR has been merged!

It is a nice way to set this animation speed!
