### ISSUE TITLE
Does this work with MM 2.18

### ISSUE THREAD

**Issue by Plainbroke** [timdows/MMM-JsonTable#31]
Can you make this work with MagicMirror 2.18 when I try to use it I get a black screen.
Removing it makes my MM work again.

**Comment by KristjanESPERANTO** [comment]
For me it's working with 2.18. Please show your config of the module :-)

**Comment by Plainbroke** [comment]
I found it is used in the MMM-GmailFeed and I can not get it to work for me
in MM 2.18...
I have tried 3 different peoples versions of the MMM-GmailFeed module and
can not get them to work..
I just get a black screen.   So I did as Sam asked and reloaded gmail to
see what errors I am getting.
The only one that is showing up in all 3 versions is from mmm-jsontable
error something about not being able to use capital letters anymore???.
 That is why the question.
How do you use MMM-JsonTable?  I am trying everything I know how to do to
get my Gmail to show up on my Mirror again.
I am pretty much a newbie, but I research a LOT before I start asking
questions...

Jeff Burdick
 "Do not regret growing older. It is a privilege denied to many."

**Comment by KristjanESPERANTO** [comment]
Okay, this is an issue of MMM-GmailFeed. I've created a PR to fix this. Till this is fixed in the module you can fix this in your installation by going in the modules folder an run `npm install request`.

**Comment by KristjanESPERANTO** [comment]
Glad I could help :slightly_smiling_face:

**Comment by timdows** [comment]
I will close this issue, at is was originated for a branch MMM-GmailFeed
