### ISSUE TITLE
Font Awesome Icons and images support

### ISSUE THREAD

**Issue by Snille** [timdows/MMM-JsonTable#4]
Hello! I'm trying out your module to display some statistics from my coffee machine.
I would like to be able to use small "icons". I'm thinking if I define in the json for example the fa-icons, se below... And also if possible, if an image is inserted that could be displayed as well...

Here is an example of my json... 

```json
{  
   "cups":[  
      {  
         "icon":"fa-calendar",
         "data":"Senaste bryggning",
         "value":"2019-03-07",
         "type":""
      },
      {  
         "icon":"fa-clock-o",
         "data":"Klockan",
         "value":"17:32:06",
         "type":""
      },
      {  
         "icon":"fa-coffee",
         "data":"Totalt antal bryggda koppar",
         "value":60,
         "type":"st"
      },
      {  
         "icon":"img=http://10.0.0.30/img/magicmirror/buttons/coffeebeans-512x512.png",
         "data":"Kostnad b\u00f6nor (alla koppar)",
         "value":319.2,
         "type":"kr"
      },
      {  
         "icon":"fa-cog",
         "data":"Kostnad b\u00f6nor \/ kopp",
         "value":5.32,
         "type":"kr"
      },
      {  
         "icon":"fa-cogs",
         "data":"Kostnad maskin \/ kopp",
         "value":408.17,
         "type":"kr"
      },
      {  
         "icon":"fa-diamond",
         "data":"Kostnad totalt \/ kopp",
         "value":413.49,
         "type":"kr"
      }
   ]
}
```

In this example I would like to get the "icons" from font awesome displayed instead of the text, and when the img= is present, the picture should be displayed instead.
Result in this case would be: 
![image](https://user-images.githubusercontent.com/1011699/53985507-104ecc00-411c-11e9-9ca4-c994f0ae62e1.png)

I hope you get what I mean. :)

Best regards Erik

**Comment by timdows** [comment]
Awesome suggestion!
Added it in commit https://github.com/timdows/MMM-JsonTable/commit/5f51e1e45ec2d1afc14720439bade5fd3240ae11

Let me know if it works for you as well

**Comment by Snille** [comment]
Hi! Good work! :) Looks great, thank you!
I'm happy with the font awesome support. It's enough. The Image was just because there are no "beans" in the font... But it's ok It's not that important! :)
Result: 
![image](https://user-images.githubusercontent.com/1011699/54084833-14eecc80-4336-11e9-9921-cb20b8f93fed.png)
