### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by spookytheripper** [timdows/MMM-JsonTable#57]
Hi,

First, thank you for creating this module, as a hobby programmer it made it very easy to implement my project into the MM without knowing anything about js.

I saw how enthusiastically you implemented the Font Awesome idea and I was hoping maybe you could help out with some basic colors.

I made a table to display Air quality information from a co2 sensor and i'd like to color code it so that if the CO2 levels are high the row is then displayed in yellow and red (depending on the levels). the other rows that display temperature and humidity should ideally stay white.

would it be possible to had a simple "color"-key to the json so that it is then changed in the table... "color":"yellow"

If not is there any other way i could implement this?

thank you

**Comment by timdows** [comment]
Quite late, but @SirStepheno has created this feature
